name: Deploy
run-name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present --workspace=app

      - name: Deploy
        uses: actions/deploy-pages@v2
