name: Deploy Application
run-name: deploy-app
on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present --workspace=app

      # - name: Save artifacts
      #   uses: actions/upload-pages-artifact@main
      #   with:
      #     path: dist/app

      - name: Deploy
        shell: bash
        run: |
          # Initialize a new git repository
          git remote add pages https://github.com/willikers/willikers.github.io.git
          # Remove all files and folders except .git and dist/app
          ls | grep -v -E 'dist|\.git' | xargs rm -rf
          # Move the contents of dist/app to the root directory
          mv dist/app/* .
          git add .
          git commit -m "Deploy application"
          git push pages main
      #   uses: actions/deploy-pages@v4
